### PR TITLE
Added completion to profiles

### PR DESCRIPTION
**Pull request by padilo**
Adds autocompletion to profiles

### CODE REVIEW

**Comment by simcap** [comment]
Thanks! 

For this one @padilo , if a file does not exists (ex: `~/.aws/config` .... not everybody has this file present unfortunately) the completion will throw out an error.

Before we merge this one the bash script should handle grep on non existing file (i.e. file exists check beforehand).

Good job! Will be very useful.

**Comment by padilo** [comment]
Cool, I'll improve that ;)

**Comment by padilo** [comment]
@simcap, should be solved now. Also rebased on top of master

**Comment by simcap** [comment]
Thanks @padilo . Merged.

**Pull request merged**
